version: '3'

services:
  db:
    image: mariadb:10.3
    environment:
      DATABASE_NAME: cse
      MYSQL_ROOT_PASSWORD: root
      DATABASE_USER: root
    volumes:
      - db-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog

volumes:
  db-data:
